services:
  postgres:
    image: postgres:15-alpine
    container_name: security-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: security_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d security_app"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: security-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: password123
      DB_NAME: security_app
      PORT: 3001
      JWT_SECRET: a345b99c128e121f0efc396945de734d
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run migrate:prod && npm start"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`staging.alu.app`)"
      - "traefik.http.routers.backend.entrypoints=web,websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"

    networks:
      - web

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://staging.alu.app/api}
    container_name: security-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-alcheemployeeportalv121copy.rule=Host(`attendance.alu.app`)"
      - "traefik.http.routers.frontend-alcheemployeeportalv121copy.service=frontend-alcheemployeeportalv121copy"
      - "traefik.http.routers.frontend-alcheemployeeportalv121copy.tls=true"
      - "traefik.http.routers.frontend-alcheemployeeportalv121copy.entrypoints=web,websecure"
      - "traefik.http.routers.frontend-alcheemployeeportalv121copy.tls.certresolver=le"
    networks:
      - web

networks: #using the traefk default network
  web:
    name: dockertraefk_default
    external: true
volumes:
  postgres_data:
